substitutions:
  devicename: girls_bedroom_eth_va

external_components:
  - source: github://esphome/esphome@94befe126bc952785994ddf8dcfd15e9c3c3ff23
    components: [ remote_base, remote_receiver, remote_transmitter, esp32_rmt, esp32_rmt_led_strip ]
    refresh: 5min  

packages:
  base_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}
  voice_board: !include 
    file: packages/va_board_2.0.yaml
    vars:
      devicename: ${devicename}
  string_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO48
      length: 405
      color_line: RGB
      name: girls_string      

#sensor:   
#  - platform: bmp280_i2c
#    temperature:
#      name: ${devicename}_ext_temp
#      oversampling: 16x
#    pressure:
#      name: ${devicename}_ext_pressure
#    address: 0x76
#    i2c_id: i2c_channel
#    update_interval: 60s  
